name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
        label: Reproduction steps
        description: "How do you trigger this bug? Please walk us through it step by step."
        value: |
          1.
          2.
          3.
          ...
        render: bash
      validations:
        required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

